<?php

namespace App\Services;

use App\Models\CommercialEvidence;
use App\Models\CustomerInterview;
use App\Models\Experiment;
use App\Models\Opportunity;
use App\Models\OpportunityStageTransition;
use App\Models\ProblemSignal;
use App\Models\Source;
use App\Support\CommercialStage;
use Carbon\CarbonImmutable;
use Illuminate\Support\Facades\DB;

/**
 * §39's weekly report, built from stored rows.
 *
 * Milestone 7's acceptance criterion is that generation is "automatic and
 * **reproducible from stored data**", and every design choice here follows from
 * the second half:
 *
 *  - **Nothing reads `now()`.** Every query is bounded by the window passed in.
 *    A report for last week must produce the same answer next month, and a
 *    single `whereDate(..., '>=', now()->subDays(7))` would quietly break that
 *    for every section it touched.
 *  - **Nothing is generated by an LLM.** §41: "Never allow AI-generated
 *    summaries to replace raw evidence." The executive summary is assembled from
 *    the same figures the sections report, so it cannot say something the rest
 *    of the document contradicts — and it renders identically every time.
 *  - **Ordering is total.** Every sort has a tiebreak on `id`, because two
 *    opportunities with the same score would otherwise come back in whatever
 *    order Postgres felt like, and the content hash would flap between runs on
 *    identical data.
 */
class ReportBuilder
{
    /** §39: "Maximum 0–2 opportunities. Do not recommend building 10 products simultaneously." */
    public const MAX_BUILD_RECOMMENDATIONS = 2;

    private const TOP_N = 5;

    public function __construct(
        private readonly CarbonImmutable $periodStart,
        private readonly CarbonImmutable $periodEnd,
    ) {}

    public static function forWeekEnding(CarbonImmutable $end): self
    {
        // Inclusive 7-day window. `subDays(6)` rather than `subWeek()` so the
        // period is exactly seven dates and consecutive weekly reports neither
        // overlap by a day nor skip one.
        return new self($end->subDays(6)->startOfDay(), $end->endOfDay());
    }

    public function build(): array
    {
        // Resolved once and reused by every section: two sections computing
        // "the opportunities in scope" separately could disagree after a
        // concurrent rescore mid-build.
        $opportunities = $this->opportunitiesInScope();
        $signalCounts = $this->signalCountsByTopic();
        $previousCounts = $this->previousSignalCountsByTopic();

        $sections = [
            'executive_summary' => [],   // filled last: it summarises the rest
            'rising_problems' => $this->risingProblems($opportunities, $signalCounts, $previousCounts),
            'commercial_opportunities' => $this->commercialOpportunities($opportunities),
            'new_signals' => $this->newSignals(),
            'buyer_evidence' => $this->buyerEvidence(),
            'opportunities_to_ignore' => $this->opportunitiesToIgnore($opportunities, $signalCounts),
            'suggested_experiments' => $this->suggestedExperiments($opportunities),
            'build_recommendation' => $this->buildRecommendation($opportunities),
        ];

        $sections['executive_summary'] = $this->executiveSummary($sections, $opportunities);

        return [
            'title' => 'Malaysia SME Opportunity Intelligence',
            'period_start' => $this->periodStart->toDateString(),
            'period_end' => $this->periodEnd->toDateString(),
            'sections' => $sections,
            'inputs' => $this->inputs($opportunities),
        ];
    }

    // ------------------------------------------------------------------ sections

    /**
     * §39's "Executive Summary — Top 3 findings".
     *
     * Assembled from what the other sections already found rather than written
     * afresh. Two reasons: it cannot then contradict the body, and it renders
     * deterministically — which an LLM summary would not (§41).
     *
     * Findings are ordered by how much they should change behaviour, not by
     * score: a payment that arrived this week matters more than a topic being
     * marginally noisier than last week, whatever the numbers say.
     */
    private function executiveSummary(array $sections, $opportunities): array
    {
        $findings = [];

        $paid = collect($sections['buyer_evidence']['paid_evidence'] ?? []);
        if ($paid->isNotEmpty()) {
            $total = $paid->sum(fn ($e) => (float) ($e['value'] ?? 0));
            $findings[] = [
                'kind' => 'commercial',
                'headline' => $paid->count() === 1
                    ? 'One payment recorded this period'
                    : "{$paid->count()} payments recorded this period",
                'detail' => $total > 0
                    ? 'MYR '.number_format($total, 2).' across '
                        .$paid->pluck('company_ref')->filter()->unique()->count().' business(es).'
                    : 'No amounts recorded against them.',
            ];
        }

        $promotions = collect($sections['buyer_evidence']['stage_changes'] ?? [])
            ->filter(fn ($t) => CommercialStage::isAdvance($t['from'] ?? 'observed', $t['to']));
        if ($promotions->isNotEmpty()) {
            $furthest = $promotions->sortByDesc(fn ($t) => CommercialStage::rank($t['to']))->first();
            $findings[] = [
                'kind' => 'stage',
                'headline' => "{$promotions->count()} stage advance(s), furthest to ".
                    (CommercialStage::LABELS[$furthest['to']] ?? $furthest['to']),
                'detail' => "{$furthest['title']} moved to ".(CommercialStage::LABELS[$furthest['to']] ?? $furthest['to']).'.',
            ];
        }

        $rising = collect($sections['rising_problems']);
        if ($rising->isNotEmpty()) {
            $top = $rising->first();
            $findings[] = [
                'kind' => 'rising',
                'headline' => "{$top['title']} is the fastest-rising problem",
                'detail' => "{$top['mentions']} mentions this period vs {$top['previous_mentions']} last "
                    ."({$top['change_label']}).",
            ];
        }

        $newSignals = collect($sections['new_signals']);
        if ($newSignals->isNotEmpty() && count($findings) < 3) {
            $findings[] = [
                'kind' => 'new',
                'headline' => $newSignals->count() === 1
                    ? 'One previously unseen problem appeared'
                    : "{$newSignals->count()} previously unseen problems appeared",
                'detail' => $newSignals->take(3)->pluck('title')->implode(', ').'.',
            ];
        }

        $top = collect($sections['commercial_opportunities']);
        if ($top->isNotEmpty() && count($findings) < 3) {
            $best = $top->first();
            $findings[] = [
                'kind' => 'ranking',
                'headline' => "{$best['title']} leads on opportunity score",
                'detail' => "Score {$best['opportunity_score']} at confidence {$best['confidence_score']}"
                    .' — '.($best['recommendation'] ?? 'no recommendation').'.',
            ];
        }

        // §39 asks for three. Fewer is reported honestly rather than padded:
        // a quiet week is a finding.
        return [
            'findings' => array_slice($findings, 0, 3),
            'quiet_period' => $findings === [],
        ];
    }

    /**
     * §39's "Rising Problems — what accelerated".
     *
     * Compares this window against the one immediately before it, so
     * "accelerated" means something measurable rather than "has a high score".
     * A topic with no prior mentions is reported as new rather than as infinite
     * growth — see `percentChange()`.
     */
    private function risingProblems($opportunities, array $current, array $previous): array
    {
        return $opportunities
            ->map(function (Opportunity $o) use ($current, $previous) {
                $now = $current[$o->topic_id] ?? 0;
                $before = $previous[$o->topic_id] ?? 0;

                return [
                    'id' => $o->id,
                    'topic' => $o->topic?->slug,
                    'title' => $o->title,
                    'mentions' => $now,
                    'previous_mentions' => $before,
                    'change_percent' => $this->percentChange($now, $before),
                    'change_label' => $this->changeLabel($now, $before),
                    'opportunity_score' => $this->score($o->opportunity_score),
                    'confidence_score' => $this->score($o->confidence_score),
                ];
            })
            // Only genuine acceleration. A topic that held steady did not
            // accelerate, and listing it under this heading would be a lie the
            // reader has to check.
            ->filter(fn (array $row) => $row['mentions'] > $row['previous_mentions'])
            ->sortByDesc(fn (array $row) => [$row['change_percent'] ?? PHP_INT_MAX, $row['mentions'], -$row['id']])
            ->take(self::TOP_N)
            ->values()
            ->all();
    }

    /** §39's "Commercial Opportunities — top ranked". */
    private function commercialOpportunities($opportunities): array
    {
        return $opportunities
            ->filter(fn (Opportunity $o) => $o->opportunity_score !== null)
            ->sortBy([['opportunity_score', 'desc'], ['id', 'asc']])
            ->take(self::TOP_N)
            ->map(fn (Opportunity $o) => [
                'id' => $o->id,
                'topic' => $o->topic?->slug,
                'title' => $o->title,
                'pain_score' => $this->score($o->pain_score),
                'commercial_score' => $this->score($o->commercial_score),
                'opportunity_score' => $this->score($o->opportunity_score),
                // §30: confidence never travels separately from the score.
                'confidence_score' => $this->score($o->confidence_score),
                'stage' => $o->status,
                'suggested_stage' => $o->suggested_status,
                'recommendation' => $o->recommendation,
                'target_buyer' => $o->target_buyer,
            ])
            ->values()
            ->all();
    }

    /**
     * §39's "New Signals — previously unseen problems".
     *
     * A topic counts as new when its *first ever* signal falls inside the
     * window. Ranking on recent activity instead would return the busiest
     * topics, which are by definition not new.
     */
    private function newSignals(): array
    {
        $firstSeen = ProblemSignal::query()
            ->select('topic_id', DB::raw('MIN(signal_date) as first_seen'), DB::raw('COUNT(*) as signal_count'))
            ->groupBy('topic_id')
            ->havingRaw('MIN(signal_date) >= ?', [$this->periodStart->toDateString()])
            ->havingRaw('MIN(signal_date) <= ?', [$this->periodEnd->toDateString()])
            ->get();

        if ($firstSeen->isEmpty()) {
            return [];
        }

        $opportunities = Opportunity::with('topic:id,slug,name')
            ->whereIn('topic_id', $firstSeen->pluck('topic_id'))
            ->get()
            ->keyBy('topic_id');

        return $firstSeen
            ->sortBy([['first_seen', 'desc'], ['topic_id', 'asc']])
            ->map(function ($row) use ($opportunities) {
                $opportunity = $opportunities->get($row->topic_id);

                return [
                    'id' => $opportunity?->id,
                    'topic' => $opportunity?->topic?->slug,
                    'title' => $opportunity?->title ?? $opportunity?->topic?->name ?? "topic {$row->topic_id}",
                    'first_seen' => (string) $row->first_seen,
                    'signals' => (int) $row->signal_count,
                    'opportunity_score' => $this->score($opportunity?->opportunity_score),
                    // A brand-new topic often has no opportunity row yet, and
                    // saying so is more useful than omitting it.
                    'scored' => $opportunity?->opportunity_score !== null,
                ];
            })
            ->values()
            ->all();
    }

    /** §39's "Buyer Evidence — recent interviews and commercial signals". */
    private function buyerEvidence(): array
    {
        $interviews = CustomerInterview::query()
            ->with('opportunity:id,title')
            ->whereBetween('interviewed_at', [$this->periodStart, $this->periodEnd])
            ->orderBy('interviewed_at')
            ->orderBy('id')
            ->get()
            ->map(fn (CustomerInterview $i) => [
                'opportunity_id' => $i->opportunity_id,
                'title' => $i->opportunity?->title,
                // Pseudonymous by design (§21) — nothing here identifies anyone.
                'company_ref' => $i->company_ref,
                'industry' => $i->industry,
                'respondent_role' => $i->respondent_role,
                'problem_confirmed' => $i->problem_confirmed,
                'pilot_interest' => $i->pilot_interest,
                'willingness_to_pay' => $i->willingness_to_pay,
                'interviewed_at' => $i->interviewed_at?->toDateString(),
            ])
            ->all();

        $evidence = CommercialEvidence::query()
            ->with('opportunity:id,title')
            ->whereBetween('occurred_at', [$this->periodStart, $this->periodEnd])
            ->orderBy('occurred_at')
            ->orderBy('id')
            ->get();

        $transitions = OpportunityStageTransition::query()
            ->with('opportunity:id,title')
            ->whereBetween('created_at', [$this->periodStart, $this->periodEnd])
            ->orderBy('created_at')
            ->orderBy('id')
            ->get()
            ->map(fn (OpportunityStageTransition $t) => [
                'opportunity_id' => $t->opportunity_id,
                'title' => $t->opportunity?->title,
                'from' => $t->from_status,
                'to' => $t->to_status,
                'suggested_at_time' => $t->suggested_status_at_time,
                'note' => $t->note,
            ])
            ->all();

        return [
            'interviews' => $interviews,
            'confirmations' => collect($interviews)->where('problem_confirmed', true)->count(),
            'evidence' => $evidence->map(fn (CommercialEvidence $e) => $this->evidenceRow($e))->all(),
            // Split out because §7 Gate 4 is emphatic that money is a different
            // grade of evidence, and burying a payment in a list of nine types
            // is how a report fails to say the one thing that mattered.
            'paid_evidence' => $evidence
                ->filter(fn (CommercialEvidence $e) => in_array($e->evidence_type, CommercialEvidence::PAID_TYPES, true))
                ->map(fn (CommercialEvidence $e) => $this->evidenceRow($e))
                ->values()
                ->all(),
            'stage_changes' => $transitions,
        ];
    }

    /**
     * §39's "Opportunities to Ignore — problems with high attention but poor
     * monetization".
     *
     * Two distinct populations, and keeping them apart matters: a topic the
     * engine scores as commercially weak is a different situation from one a
     * human has already decided to drop, and the second should not be
     * re-litigated every week.
     */
    private function opportunitiesToIgnore($opportunities, array $signalCounts): array
    {
        $attentionThreshold = 3;

        $poorlyMonetizable = $opportunities
            ->filter(function (Opportunity $o) use ($signalCounts, $attentionThreshold) {
                $mentions = $signalCounts[$o->topic_id] ?? 0;
                $commercial = $o->commercial_score === null ? null : (float) $o->commercial_score;

                return $mentions >= $attentionThreshold
                    && $commercial !== null
                    && $commercial < 40;   // §35's IGNORE threshold
            })
            ->sortBy([['commercial_score', 'asc'], ['id', 'asc']])
            ->map(fn (Opportunity $o) => [
                'id' => $o->id,
                'title' => $o->title,
                'mentions' => $signalCounts[$o->topic_id] ?? 0,
                'pain_score' => $this->score($o->pain_score),
                'commercial_score' => $this->score($o->commercial_score),
                'reason' => 'Attention without a commercial case — commercial score below 40 (§35).',
            ])
            ->values()
            ->all();

        $humanIgnored = $opportunities
            ->filter(fn (Opportunity $o) => $o->recommendation === 'IGNORE')
            ->sortBy('id')
            ->map(fn (Opportunity $o) => [
                'id' => $o->id,
                'title' => $o->title,
                'reason' => 'Recommendation is IGNORE.',
            ])
            ->values()
            ->all();

        return ['poorly_monetizable' => $poorlyMonetizable, 'already_ignored' => $humanIgnored];
    }

    /**
     * §39's "Suggested Experiments — what to validate".
     *
     * Derived from where each opportunity is stuck in §7's gates, because "what
     * to validate" is exactly "what is the next gate and what would satisfy it".
     * Experiments already running are listed separately so the report suggests
     * work rather than re-suggesting work in progress.
     */
    private function suggestedExperiments($opportunities): array
    {
        $running = Experiment::query()
            ->with('opportunity:id,title')
            ->whereIn('status', ['planned', 'running'])
            ->orderBy('id')
            ->get()
            ->map(fn (Experiment $e) => [
                'opportunity_id' => $e->opportunity_id,
                'title' => $e->opportunity?->title,
                'experiment_type' => $e->experiment_type,
                'hypothesis' => $e->hypothesis,
                'success_metric' => $e->success_metric,
                'status' => $e->status,
            ])
            ->all();

        $concluded = Experiment::query()
            ->with('opportunity:id,title')
            ->where('status', 'completed')
            ->whereBetween('completed_at', [$this->periodStart, $this->periodEnd])
            ->orderBy('id')
            ->get()
            ->map(fn (Experiment $e) => [
                'opportunity_id' => $e->opportunity_id,
                'title' => $e->opportunity?->title,
                'experiment_type' => $e->experiment_type,
                'succeeded' => $e->succeeded,
                'result' => $e->result,
            ])
            ->all();

        $withRunning = collect($running)->pluck('opportunity_id')->unique()->all();

        $suggested = $opportunities
            // Only worth suggesting work for opportunities that look worth the
            // time. Below this the answer is "leave it", not "run a landing page".
            ->filter(fn (Opportunity $o) => $o->opportunity_score !== null && (float) $o->opportunity_score >= 45)
            ->reject(fn (Opportunity $o) => in_array($o->id, $withRunning, true))
            ->sortBy([['opportunity_score', 'desc'], ['id', 'asc']])
            ->take(self::TOP_N)
            ->map(function (Opportunity $o) {
                $evidence = $o->evidenceSummary();
                $nextGate = $this->nextUnmetGate($o, $evidence);

                return [
                    'opportunity_id' => $o->id,
                    'title' => $o->title,
                    'stage' => $o->status,
                    'next_gate' => $nextGate['stage'],
                    'blocked_by' => $nextGate['requirement'],
                    'suggested_experiment' => $nextGate['experiment'],
                ];
            })
            ->filter(fn (array $row) => $row['next_gate'] !== null)
            ->values()
            ->all();

        return ['suggested' => $suggested, 'in_progress' => $running, 'concluded_this_period' => $concluded];
    }

    /**
     * §39's "Build Recommendation — maximum 0–2 opportunities".
     *
     * Only §35's two most advanced recommendations qualify, and the cap is hard.
     * §39: "Do not recommend building 10 products simultaneously." Anything
     * that would have been third is reported as deferred rather than dropped, so
     * the cap is visible as a choice rather than looking like the whole picture.
     */
    private function buildRecommendation($opportunities): array
    {
        $eligible = $opportunities
            ->filter(fn (Opportunity $o) => in_array($o->recommendation, ['PRODUCTIZE', 'SELL_PILOT'], true))
            ->sortBy([
                // PRODUCTIZE before SELL_PILOT regardless of score: §7 Gate 5
                // makes repeatability the thing that licenses real investment.
                fn (Opportunity $o) => $o->recommendation === 'PRODUCTIZE' ? 0 : 1,
            ])
            ->sortBy([['recommendation', 'asc'], ['opportunity_score', 'desc'], ['id', 'asc']])
            ->values();

        $recommended = $eligible->take(self::MAX_BUILD_RECOMMENDATIONS);

        return [
            'recommended' => $recommended->map(fn (Opportunity $o) => [
                'id' => $o->id,
                'title' => $o->title,
                'recommendation' => $o->recommendation,
                'opportunity_score' => $this->score($o->opportunity_score),
                'confidence_score' => $this->score($o->confidence_score),
                'stage' => $o->status,
            ])->all(),
            'deferred_by_cap' => $eligible->skip(self::MAX_BUILD_RECOMMENDATIONS)
                ->map(fn (Opportunity $o) => ['id' => $o->id, 'title' => $o->title])
                ->values()
                ->all(),
            'cap' => self::MAX_BUILD_RECOMMENDATIONS,
            'note' => $recommended->isEmpty()
                ? 'Nothing has cleared enough of §7\'s gates to justify building. That is a valid answer.'
                : null,
        ];
    }

    // ------------------------------------------------------------------ helpers

    private function evidenceRow(CommercialEvidence $e): array
    {
        return [
            'opportunity_id' => $e->opportunity_id,
            'title' => $e->opportunity?->title,
            'evidence_type' => $e->evidence_type,
            'strength' => $e->strength,
            'value' => $e->value === null ? null : (float) $e->value,
            'currency' => $e->currency,
            'company_ref' => $e->company_ref,
            'occurred_at' => $e->occurred_at?->toDateString(),
        ];
    }

    /** The first gate this opportunity has not satisfied, plus what would satisfy it. */
    private function nextUnmetGate(Opportunity $o, array $evidence): array
    {
        $experiments = [
            'buyer_identified' => 'Write down who holds the budget for this — no experiment needed, just a decision.',
            'problem_validated' => 'customer_interview: talk to one business and record whether the problem is real.',
            'commercially_validated' => 'cold_outreach: reach a second independent business, and put a proposal in front of one of them.',
            'paid_pilot' => 'paid_pilot: ask for money. §7 Gate 4 — intent is not evidence.',
            'repeatable_solution' => 'cold_outreach: find a second business with substantially the same workflow problem.',
        ];

        $currentRank = CommercialStage::rank($o->status);

        foreach (CommercialStage::GATED as $stage => $requirement) {
            if (CommercialStage::rank($stage) <= $currentRank) {
                continue;
            }

            [$satisfied] = CommercialStage::gateCheck($stage, $evidence);
            if (! $satisfied) {
                return [
                    'stage' => $stage,
                    'requirement' => $requirement,
                    'experiment' => $experiments[$stage] ?? null,
                ];
            }

            // Gate satisfied but the human has not promoted yet: the suggested
            // action is the promotion, not more evidence.
            return [
                'stage' => $stage,
                'requirement' => "Already satisfied — promote to {$stage} when you are ready.",
                'experiment' => null,
            ];
        }

        return ['stage' => null, 'requirement' => null, 'experiment' => null];
    }

    private function opportunitiesInScope()
    {
        // Every scored opportunity, not only those with signals in the window.
        // A topic that went quiet this week is still a live opportunity, and
        // "Opportunities to Ignore" specifically needs to see it.
        return Opportunity::with('topic:id,slug,name')->orderBy('id')->get();
    }

    private function signalCountsByTopic(): array
    {
        return ProblemSignal::query()
            ->select('topic_id', DB::raw('COUNT(*) as n'))
            ->whereBetween('signal_date', [$this->periodStart->toDateString(), $this->periodEnd->toDateString()])
            ->groupBy('topic_id')
            ->pluck('n', 'topic_id')
            ->map(fn ($n) => (int) $n)
            ->all();
    }

    private function previousSignalCountsByTopic(): array
    {
        $length = $this->periodStart->diffInDays($this->periodEnd) + 1;
        $previousEnd = $this->periodStart->subDay();
        $previousStart = $previousEnd->subDays($length - 1);

        return ProblemSignal::query()
            ->select('topic_id', DB::raw('COUNT(*) as n'))
            ->whereBetween('signal_date', [$previousStart->toDateString(), $previousEnd->toDateString()])
            ->groupBy('topic_id')
            ->pluck('n', 'topic_id')
            ->map(fn ($n) => (int) $n)
            ->all();
    }

    /**
     * Null rather than a number when there is no prior baseline.
     *
     * Growth from zero has no finite percentage, and returning a large number
     * would make a topic's first two mentions outrank a genuine surge. The
     * report says "new" instead, which is the true statement.
     */
    private function percentChange(int $now, int $before): ?float
    {
        if ($before === 0) {
            return null;
        }

        return round((($now - $before) / $before) * 100, 1);
    }

    private function changeLabel(int $now, int $before): string
    {
        if ($before === 0) {
            return 'new this period';
        }

        $change = $this->percentChange($now, $before);

        return ($change > 0 ? '+' : '').$change.'%';
    }

    private function score($value): ?float
    {
        return $value === null ? null : (float) $value;
    }

    /**
     * What the report was built from.
     *
     * Without this, "reproducible" is unfalsifiable. The scoring config version
     * matters most: the same window scored under different weights legitimately
     * produces a different report, and a reader comparing two needs to be able
     * to see that rather than conclude the data changed.
     */
    private function inputs($opportunities): array
    {
        return [
            'scoring_config_versions' => $opportunities
                ->pluck('scoring_config_version')
                ->filter()
                ->unique()
                ->sort()
                ->values()
                ->all(),
            'builder_version' => 'report_weekly_v1',
            'counts' => [
                'opportunities' => $opportunities->count(),
                'scored_opportunities' => $opportunities->whereNotNull('opportunity_score')->count(),
                'signals_in_period' => array_sum($this->signalCountsByTopic()),
                'interviews_in_period' => CustomerInterview::whereBetween(
                    'interviewed_at', [$this->periodStart, $this->periodEnd]
                )->count(),
                'evidence_in_period' => CommercialEvidence::whereBetween(
                    'occurred_at', [$this->periodStart, $this->periodEnd]
                )->count(),
                'enabled_sources' => Source::where('enabled', true)->count(),
            ],
        ];
    }
}
